### ISSUE TITLE
Error:1C800068:Provider routines: :Wrong final block

### ISSUE THREAD

**Issue by tenzeroauto** [inwaar/gree-hvac-client#17]
Error: error:1C80006B:Provider routines::wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at EncryptionService.decrypt (C:\Users\xxxxxxxx\.node-red\node_modules\gree-hvac-client\lib\encryption-service.js:43:42)
    at Client._handleResponse (C:\Users\xxxxxxxx\.node-red\node_modules\gree-hvac-client\lib\client.js:291:46)
    at Socket.<anonymous> (C:\Users\xxxxxxxx\.node-red\node_modules\gree-hvac-client\lib\client.js:113:52)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8)

I get this error when trying to connect to a gree Hi wall AC.

**Comment by apachler** [comment]
Heads-up: a maintained fork lives at **apachler/gree-hvac-client**. It already
  prevents the decrypt failure from crashing the process (it's emitted as an
  `error` event instead). Full **AES-GCM support for the scan/discovery command**
  on newer devices (Vaillant VAI etc.) is tracked as the top open item but isn't
  implemented yet — it needs a test device or captured packets. If you have one and
  can help verify, please chime in.
